---
AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a S3 bucket, KMS key, KMS alias that can be used by the WebPortal CodePipeline.

Parameters:
  SharedServiceAccountId:
    Type: String
    Default: "355189840595"
  TestAccountId:
    Type: String
    Default: "842337631775"
  StageAccountId:
    Type: String
    Default: "281782457076"
  ProdAccountId:
    Type: String
    Default: "009576122059"
  SharedServiceAccountCMKAdminRoleName:
    Type: String
    Default: 1S-Admins
  GitHubRepoName:
    Type: String
    Default: codepipeline-demo
  PipelineArtifactsBucketName:
    Type: String
    Default: 1s-webportal-codepipeline-us-east-1
Resources:
  ####################################################
  ## Resources - KMS - CMK
  ####################################################
  CMKKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Webportal codepipeline CMK."
      KeyPolicy:
        Version: "2012-10-17"
        Id: "key-default-1"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${SharedServiceAccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${SharedServiceAccountId}:role/${SharedServiceAccountCMKAdminRoleName}"
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"

          - Sid: "Allow use of the key"
            Effect: "Allow"
            Principal: "*"
            Action:
              - "kms:DescribeKey"
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey"
              - "kms:GenerateDataKeyWithoutPlaintext"
            Resource: "*"
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal: "*"
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: "*"
            Condition:
              Bool:
                kms:GrantIsForAWSResource: "true"

  CMKAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${GitHubRepoName}-CMK
      TargetKeyId:
        Ref: CMKKey

  ####################################################
  ## Resources - S3 Bucket - PipelineArtifactsBucket
  ####################################################
  CodePipelineS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref PipelineArtifactsBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref CMKKey
  ####################################################
  ## Resources - S3 Bucket Policy
  ####################################################
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CodePipelineS3Bucket
      PolicyDocument:
        Statement:
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action:
              - s3:PutObject
            Resource:
              - !Sub arn:aws:s3:::${PipelineArtifactsBucketName}/*
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: aws:kms
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:aws:s3:::${PipelineArtifactsBucketName}/*
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: ""
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${TestAccountId}:root
                - !Sub arn:aws:iam::${StageAccountId}:root
                - !Sub arn:aws:iam::${ProdAccountId}:root

            Action:
              - s3:Get*
              - s3:Put*
            Resource:
              - !Sub arn:aws:s3:::${PipelineArtifactsBucketName}/*
          - Sid: ""
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${TestAccountId}:root
                - !Sub arn:aws:iam::${StageAccountId}:root
                - !Sub arn:aws:iam::${ProdAccountId}:root
            Action: s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${PipelineArtifactsBucketName}
Outputs:
  CMKKeyArn:
    Description: The arn of the CodePipeline CMK.
    Value: !GetAtt CMKKey.Arn
    Export:
      Name: CMKKeyArn
  CMKKeyAlias:
    Description: The alias of the CodePipeline CMK.
    Value: !Ref CMKAlias
    Export:
      Name: CMKKeyAlias
  PipelineArtifactsBucketName:
    Description: The name of the codepipeline artifacts bucket.
    Value: !Ref PipelineArtifactsBucketName
    Export:
      Name: PipelineArtifactsBucketName
  SharedServiceAccountId:
    Description: The id of the shared-services account.
    Value: !Ref SharedServiceAccountId
    Export:
      Name: SharedServiceAccountId
  TestAccountId:
    Description: The id of the test account.
    Value: !Ref TestAccountId
    Export:
      Name: TestAccountId
  StageAccountId:
    Description: The id of the stage account.
    Value: !Ref StageAccountId
    Export:
      Name: StageAccountId
  ProdAccountId:
    Description: The id of the prod account.
    Value: !Ref ProdAccountId
    Export:
      Name: ProdAccountId
