AWSTemplateFormatVersion: 2010-09-09
Description: create the CodeDeploy application, deployment group, and service role used by CodeDeploy.

####################################################
# Parameters
####################################################
Parameters:
  GitHubRepoName:
    Type: String
    Default: codepipeline-demo

  SharedServiceAccountId:
    Type: String
    Default: "355189840595"

####################################################
# Resources
####################################################
Resources:
  ####################################################
  ## Resources - IAM
  ####################################################
  CrossAccountCodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CrossAccountCodeDeployServiceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
          - Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${SharedServiceAccountId}:root"
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
      Path: /
  CrossAccountCodeDeployPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CrossAccountCodeDeployPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObjectAcl
            Resource:
              - !Join [
                  "",
                  [
                    "arn:aws:s3:::",
                    !ImportValue PipelineArtifactsBucketName,
                    "/*",
                  ],
                ]
              - !Join [
                  "",
                  ["arn:aws:s3:::", !ImportValue PipelineArtifactsBucketName],
                ]

          - Effect: Allow
            Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:GetApplicationRevision
              - codedeploy:RegisterApplicationRevision
            Resource: "*"
      Roles:
        - !Ref CrossAccountCodeDeployServiceRole

  ####################################################
  ## Resources - CodeDeploy
  ####################################################
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub ${GitHubRepoName}-CodeDeploy-Application
      ComputePlatform: Server

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      DeploymentGroupName: !Sub ${GitHubRepoName}-DeploymentGroup
      AutoScalingGroups:
        - !ImportValue WebPortal-ASGName
      ServiceRoleArn: !GetAtt CrossAccountCodeDeployServiceRole.Arn
